### ISSUE TITLE
pdf to csv

### ISSUE THREAD

**Issue by KAPPS-** [developmentseed/open-elections#4]
@albert-decatur any bash wizardry to convert this 1,800 page pdf table to csv to make it more useful? @dinicholson and I have been fooling around w/ tabula but it is laborious.

https://github.com/developmentseed/open-elections/blob/master/Uganda/0-Final_Presidential_Results_Polling%20Station.pdf

**Comment by drewbo** [comment]
Tabula is a disaster with this because of the format and trying to grab the areas graphically. I'm starting to have some success [pdfminer](https://github.com/euske/pdfminer) and can post the script when it's ready

**Comment by dinicholson** [comment]
Csv attached for the Apac district (pg 2-18) using Tabula ("original" setting). Definitely not perfect, some shifting columns, but nearly there. A script that breaks the pdf into ~111 manageable files by district + a bit of manual work with tabula might do it.

[Apac_District_Uganda_2016_Elections.txt](https://github.com/developmentseed/open-elections/files/147348/Apac_District_Uganda_2016_Elections.txt)

**Comment by drewbo** [comment]
Good stuff @dinicholson.

111 files still doesn't sound super manageable. My script should be there in a few (but will run pretty slowly)

**Comment by drewbo** [comment]
https://gist.github.com/drewbo/108fe2d99223a131ad8c

I'm going to start editing it to run over (1) multiple pages and then (2) over the larger pdf (right now it's on a subsection). It also needs to cut out the headers and fix a few one cell off errors

**Comment by drewbo** [comment]
Script should now work over the whole file with just a few mismatches. I'd like to optimize first (the `list(enumerate...` construction might be huge over the whole file?) and then run on the whole PDF

**Comment by drewbo** [comment]
Latest version of that script (with plenty more regex to split columns better) is running now, will update once I have a real result

**Comment by dinicholson** [comment]
@drewbo Sounds good. In case it's of any use, I noticed that on the Uganda Elections Commission website the results were broken into pdf files by district: http://www.ec.or.ug/?q=2016-presidential-results-district-polling-station

**Comment by drewbo** [comment]
CSV and scripts at https://github.com/developmentseed/open-elections/tree/master/Uganda
